# Generated by Django 2.2.3 on 2019-07-27 18:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('freedomhouse_score', models.FloatField(blank=True, null=True)),
                ('quality_of_life_index', models.FloatField(blank=True, null=True)),
                ('purchasing_power_index', models.FloatField(blank=True, null=True)),
                ('safety_index', models.FloatField(blank=True, null=True)),
                ('health_care_index', models.FloatField(blank=True, null=True)),
                ('cost_of_living_index', models.FloatField(blank=True, null=True)),
                ('property_price_to_income_ratio', models.FloatField(blank=True, null=True)),
                ('traffic_commute_time_index', models.FloatField(blank=True, null=True)),
                ('pollution_index', models.FloatField(blank=True, null=True)),
                ('climate_index', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
